"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { AnalyticsCharts } from "@/components/analytics-charts"
import UserFollowersTable from "@/components/user-followers-table"
import { Button } from "@/components/ui/button"
import { ShieldCheck, ArrowLeft, Upload } from "lucide-react"
import type { Follower } from "@/lib/mock-data"

export default function DashboardPage() {
  const router = useRouter()
  const [data, setData] = useState<Follower[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const storedData = localStorage.getItem("myxfollowing_data")
    if (storedData) {
      try {
        const parsedData = JSON.parse(storedData)
        setData(parsedData)
      } catch (e) {
        console.error("Failed to parse data", e)
      }
    }
    setLoading(false)
  }, [])

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    )
  }

  if (data.length === 0) {
    return (
      <div className="min-h-screen bg-background flex flex-col items-center justify-center p-4">
        <h2 className="text-2xl font-bold mb-4">No Data Found</h2>
        <p className="text-muted-foreground mb-8 text-center max-w-md">
          Please upload the JSON file generated by the myxfollowing Chrome Extension to view your dashboard.
        </p>
        <div className="flex gap-4">
          <Button variant="outline" onClick={() => router.push("/")}>
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
          <Button onClick={() => document.getElementById("file-upload-dash")?.click()}>
            <Upload className="mr-2 h-4 w-4" />
            Upload JSON
          </Button>
          <input
            id="file-upload-dash"
            type="file"
            accept=".json"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0]
              if (!file) return
              const reader = new FileReader()
              reader.onload = (ev) => {
                try {
                  const json = ev.target?.result as string
                  const newData = JSON.parse(json)
                  localStorage.setItem("myxfollowing_data", JSON.stringify(newData))
                  setData(newData)
                } catch (err) {
                  alert("Invalid JSON")
                }
              }
              reader.readAsText(file)
            }}
          />
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background text-foreground font-sans selection:bg-blue-500/30">
      {/* Header */}
      <header className="border-b border-border bg-card/50 backdrop-blur-xl sticky top-0 z-50">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => router.push("/")}>
            <ShieldCheck className="h-6 w-6 text-blue-500" />
            <h1 className="text-xl font-bold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
              myxfollowing
            </h1>
          </div>
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="sm" onClick={() => router.push("/")}>
              Log out
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 space-y-8">
        {/* Stats Overview */}
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <div className="p-6 rounded-xl bg-card border border-border shadow-sm">
            <div className="text-sm font-medium text-muted-foreground">Total Users Scraped</div>
            <div className="text-3xl font-bold mt-2">{data.length}</div>
          </div>
          <div className="p-6 rounded-xl bg-card border border-border shadow-sm">
            <div className="text-sm font-medium text-muted-foreground">Followers</div>
            <div className="text-3xl font-bold mt-2 text-emerald-500">
              {data.filter((u) => u.status === "Follower" || u.status === "follower").length}
            </div>
          </div>
          <div className="p-6 rounded-xl bg-card border border-border shadow-sm">
            <div className="text-sm font-medium text-muted-foreground">Following</div>
            <div className="text-3xl font-bold mt-2 text-blue-500">
              {data.filter((u) => u.status === "Following" || u.status === "following").length}
            </div>
          </div>
          <div className="p-6 rounded-xl bg-card border border-border shadow-sm">
            <div className="text-sm font-medium text-muted-foreground">Blocked</div>
            <div className="text-3xl font-bold mt-2 text-red-500">
              {data.filter((u) => u.status === "Blocked" || u.status === "blocked").length}
            </div>
          </div>
        </div>

        {/* Charts Section */}
        <AnalyticsCharts followers={data} />

        {/* Table Section */}
        <UserFollowersTable followers={data} />
      </main>
    </div>
  )
}
